### ISSUE TITLE
PHP7.4 - Zend Assertion Warning

### ISSUE THREAD

**Issue by necrogami** [Artefact2/centralcasting#2]
`PHP Warning:  zend.assertions may be completely enabled or disabled only in php.ini in /mnt/c/Users/djnec/code/centralcasting/inc/root.php on line 23`

I keep getting that code when running the files against PHP7.4

**Comment by Artefact2** [comment]
Fixed in e2d6368cda88be72a10da89e8943583af4e84abb. Thanks for reporting.
