### ISSUE TITLE
101 - 19

### ISSUE THREAD

**Issue by necrogami** [Artefact2/centralcasting#3]
A roll of 19 on table 101 should be crossbreed according to the second edition of the book.

> Crossbreed: A crossbreed has mixed racial blood that combines elements from a mixed ancestry. These characters are sometimes outcasts or loners, never fully blending in to any society from which they hail. Other crossbreeds choose to identify themselves with one society, sometimes at the cost of forsaking all ties with part of their heritage.
Not all crossbreeds are half one race and half another. Many are primarily descendants of one race, but can trace their lineage to a pureblood of another race a few or more generations back. Decide the percentage of your character's racial mix, or roll 20 percentile dice, using the result to give an approximate indication of the balance.
To find out your character's mixed lineage, roll two more times on table 101a. If your result is "Human" both times, then your character has both human and elven blood. If any other race is rolled twice, your character is a mix between that race and humanity. If one of your results is "Crossbreed" again, your character may have blood from more than two races. Otherwise, your character's lineage stems from both races you roll.
Culture: Culture level will depend on the society in which the character was raised. Choose one of the character's races.
As with culture, the character's event table depends on which race dominated his upbringing.

**Comment by Artefact2** [comment]
Done in bb9620e3dd3e659169dfb8002eb9e74bb2709fbc. Thank you for the suggestion.
