### ISSUE TITLE
failed rerolls

### ISSUE THREAD

**Issue by necrogami** [Artefact2/centralcasting#7]
$ make 
./gendata 1000 > datap0.json
....................................................................................................
./gendata 1000 > datap1.json
....................................................................................................
./gendata 1000 > datap2.json
....................................................................................................
./gendata 1000 > datap3.json
....................................................................................................
./gendata 1000 > datap4.json
....................................................................................................
./gendata 1000 > datap5.json
....................................................................................................
./gendata 1000 > datap6.json
....................................................................................................
./gendata 1000 > datap7.json
....................................................................................................
./gendata 1000 > datap8.json
..................................................................err:tableexec:wiping visited ranges after 10 failed rerolls in 870
..................................

**Comment by Artefact2** [comment]
That's what the book wants. Over a huge number of runs there's bound to be some edge cases.
